In [35]:
import os
import pandas as pd

In [36]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gn6wsrGe83RuYuYowedF2lvCwh1T1XVy' -O referral_event.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1y7tFm1itlDE7IKYvroDPeIo1d1QLKEpl' -O users.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1lw0gj8r-bpiEhMCQWRDfyX_FUv2LfkWn' -O event_logs.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1svKqCsxe9xT8SFDZEMsR_UumySU9GhIV' -O plan_history.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1pV1XYnTiB5BkS_OA0MLJzzd3ZYvTBbw1' -O payment_transactions.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=11WpStH1sOK8-G0Hk0NwPxkV57gGEQSHF' -O ab_assignment.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1lCP2B7UM87G-QhsBFDuNhsQ6vHvQ3opV' -O campaigns.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1hXhwil5GMzvUSzhOKnM3A0dv7CHh0z8r' -O push_events.csv
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1safgIboJV594mau8CW5qfosiOVoSf9LU' -O chat_events.csv


--2025-08-11 06:11:29--  https://docs.google.com/uc?export=download&id=1gn6wsrGe83RuYuYowedF2lvCwh1T1XVy
Resolving docs.google.com (docs.google.com)... 173.194.206.113, 173.194.206.138, 173.194.206.101, ...
Connecting to docs.google.com (docs.google.com)|173.194.206.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gn6wsrGe83RuYuYowedF2lvCwh1T1XVy&export=download [following]
--2025-08-11 06:11:29--  https://drive.usercontent.google.com/download?id=1gn6wsrGe83RuYuYowedF2lvCwh1T1XVy&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.189.132, 2607:f8b0:4001:c6c::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.189.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151952 (148K) [application/octet-stream]
Saving to: ‘referral_event.csv’

referral_event.csv  100%[===================>] 148.39K  --.-

In [37]:
ab_assignment = pd.read_csv('ab_assignment.csv')
ab_assignment

assignment_id           user_id experiment_id  experiment_name  \
0     ab_c87e6ef83a01  usr_fe5b5c4844cb    exp_202501       pricing_ab   
1     ab_43ea9eae6ffd  usr_081b7e4e7569    exp_202501       pricing_ab   
2     ab_c1b1dcfe7e39  usr_6d79daab8e89    exp_202501       pricing_ab   
3     ab_64433e3f7806  usr_582bbacbd485    exp_202501       pricing_ab   
4     ab_d1235d742468  usr_f69b37b87079    exp_202501       pricing_ab   
...               ...               ...           ...              ...   
1412  ab_0cc93a223242  usr_9619dad3a150    exp_202503  checkout_design   
1413  ab_39109e640637  usr_7f238df0fde2    exp_202503  checkout_design   
1414  ab_4a45a5f6b2e6  usr_75b412488b44    exp_202503  checkout_design   
1415  ab_9ac65ea25fca  usr_49c3e69168e0    exp_202503  checkout_design   
1416  ab_35c24922a26d  usr_9cf068416914    exp_202503  checkout_design   

       variant          assigned_at  
0            A  2025-05-01 04:30:48  
1            A  2025-05-01 03:50:23  
2            B  2025-05-01 23:09:59  
3            B  2025-05-01 23:08:32  
4            A  2025-05-01 22:55:36  
...        ...                  ...  
1412  redesign  2025-07-21 03:26:17  
1413  redesign  2025-07-21 00:17:00  
1414  redesign  2025-07-21 23:01:15  
1415  redesign  2025-07-21 18:46:06  
1416  redesign  2025-07-21 03:53:20  

[1417 rows x 6 columns]

In [38]:
users = pd.read_csv('users.csv')
users

user_id           created_at         last_seen_at  \
0      usr_6b87a57bd775  2025-02-09 12:50:00  2025-07-09 00:05:00   
1      usr_b95ee57a273a  2024-12-09 20:57:00  2025-07-19 09:29:00   
2      usr_fc7ffc4130f7  2025-01-07 02:18:00  2025-07-20 12:57:00   
3      usr_f0dbe9c02021  2025-01-25 11:14:00  2025-07-09 03:16:00   
4      usr_6f08473e5134  2025-01-30 02:22:00  2025-07-03 02:55:00   
...                 ...                  ...                  ...   
22540  usr_7c2e7de25487  2025-07-21 09:33:26  2025-07-21 09:33:26   
22541  usr_53fc5b5c27e3  2025-07-21 14:48:07  2025-07-21 14:48:07   
22542  usr_2a0e09d7a5d0  2025-07-21 15:12:12  2025-07-21 15:12:12   
22543  usr_66d96508fcfc  2025-07-21 00:16:38  2025-07-21 00:16:38   
22544  usr_1f3bed337717  2025-07-21 05:49:44  2025-07-21 09:37:00   

                         email acquisition_source subscription_plan  \
0        jinhyeonu@example.net           referral              none   
1             wgim@example.com           referral        annual_pro   
2         coejaeho@example.com       facebook_ads       monthly_pro   
3             ngim@example.com         google_cpc       monthly_pro   
4          gimujin@example.com             direct              none   
...                        ...                ...               ...   
22540     caeweoni@example.org       facebook_ads              none   
22541   yumyeongja@example.net           referral              none   
22542  yeongjinsin@example.org             direct              none   
22543    anyeongsu@example.com            organic              none   
22544     baegujin@example.net             direct              none   

      plan_status device_type      plan_start_date plan_end_date gender  \
0            none         web                  NaN           NaN      M   
1          active     android  2024-12-16 20:57:00           NaN      M   
2          active         ios           2025-05-16           NaN      M   
3          active     android  2025-01-26 11:14:00           NaN      F   
4            none     android                  NaN           NaN      M   
...           ...         ...                  ...           ...    ...   
22540    trialing         web                  NaN           NaN      F   
22541    trialing         ios                  NaN           NaN      M   
22542    trialing     android                  NaN           NaN      F   
22543    trialing         web                  NaN           NaN      M   
22544    trialing     android                  NaN           NaN      F   

      age_group  age campaign_id utm_source utm_campaign  
0           30s   39     cmp_003     google        sem24  
1           30s   35     cmp_001   facebook     spring24  
2           10s   16     cmp_003     google        sem24  
3           40s   48     cmp_001   facebook     spring24  
4           30s   31     cmp_001   facebook     spring24  
...         ...  ...         ...        ...          ...  
22540       60s  103     cmp_001   facebook     spring24  
22541       40s   45     cmp_001   facebook     spring24  
22542       50s   57     cmp_002   referral    ref_buddy  
22543       40s   43     cmp_003     google        sem24  
22544       20s   26     cmp_002   referral    ref_buddy  

[22545 rows x 16 columns]

In [91]:
ab_df = pd.merge(users, ab_assignment, on='user_id', how='inner')
ab_df

user_id           created_at         last_seen_at  \
0     usr_fe5b5c4844cb  2025-05-01 04:30:48  2025-05-12 01:34:00   
1     usr_081b7e4e7569  2025-05-01 03:50:23  2025-07-18 22:45:00   
2     usr_6d79daab8e89  2025-05-01 23:09:59  2025-07-17 11:00:00   
3     usr_582bbacbd485  2025-05-01 23:08:32  2025-05-31 04:02:00   
4     usr_f69b37b87079  2025-05-01 22:55:36  2025-07-13 22:27:00   
...                ...                  ...                  ...   
1412  usr_9619dad3a150  2025-07-21 03:26:17  2025-07-21 03:26:17   
1413  usr_7f238df0fde2  2025-07-21 00:17:00  2025-07-21 00:17:00   
1414  usr_75b412488b44  2025-07-21 23:01:15  2025-07-21 23:01:15   
1415  usr_49c3e69168e0  2025-07-21 18:46:06  2025-07-21 09:59:00   
1416  usr_9cf068416914  2025-07-21 03:53:20  2025-07-21 03:53:20   

                         email acquisition_source subscription_plan  \
0       myeongja96@example.org           referral              none   
1          hayun36@example.org            organic     monthly_basic   
2     seonyeonggim@example.org         google_cpc     monthly_basic   
3        isangceol@example.org         google_cpc              none   
4           doyuni@example.com       facebook_ads       monthly_pro   
...                        ...                ...               ...   
1412     bagjuweon@example.net         google_cpc              none   
1413     gimjiweon@example.org         google_cpc              none   
1414  gimeungyeong@example.com         google_cpc              none   
1415          sgim@example.com         google_cpc              none   
1416   jeongsuggim@example.org         google_cpc              none   

     plan_status device_type plan_start_date plan_end_date  ... age_group  \
0           none         web             NaN           NaN  ...       20s   
1         active     android      2025-05-09           NaN  ...       50s   
2         active         ios      2025-05-12           NaN  ...       10s   
3           none         web             NaN           NaN  ...       30s   
4         active     android      2025-05-09           NaN  ...       10s   
...          ...         ...             ...           ...  ...       ...   
1412    trialing     android             NaN           NaN  ...       10s   
1413    trialing         web             NaN           NaN  ...       40s   
1414    trialing     android             NaN           NaN  ...       30s   
1415    trialing         web             NaN           NaN  ...       50s   
1416    trialing         ios             NaN           NaN  ...       60s   

      age  campaign_id utm_source utm_campaign    assignment_id experiment_id  \
0      28      cmp_003     google        sem24  ab_c87e6ef83a01    exp_202501   
1      53      cmp_003     google        sem24  ab_43ea9eae6ffd    exp_202501   
2      13      cmp_003     google        sem24  ab_c1b1dcfe7e39    exp_202501   
3      38      cmp_001   facebook     spring24  ab_64433e3f7806    exp_202501   
4      13      cmp_002   referral    ref_buddy  ab_d1235d742468    exp_202501   
...   ...          ...        ...          ...              ...           ...   
1412   10      cmp_003     google        sem24  ab_0cc93a223242    exp_202503   
1413   46      cmp_001   facebook     spring24  ab_39109e640637    exp_202503   
1414   31      cmp_001   facebook     spring24  ab_4a45a5f6b2e6    exp_202503   
1415   55      cmp_002   referral    ref_buddy  ab_9ac65ea25fca    exp_202503   
1416  101      cmp_001   facebook     spring24  ab_35c24922a26d    exp_202503   

      experiment_name   variant          assigned_at  
0          pricing_ab         A  2025-05-01 04:30:48  
1          pricing_ab         A  2025-05-01 03:50:23  
2          pricing_ab         B  2025-05-01 23:09:59  
3          pricing_ab         B  2025-05-01 23:08:32  
4          pricing_ab         A  2025-05-01 22:55:36  
...               ...       ...                  ...  
1412  checkout_design  redesign  2025-07-21 03:26:17  
1413  c

In [53]:
ab_df.dtypes

user_id               object
created_at            object
last_seen_at          object
email                 object
acquisition_source    object
subscription_plan     object
plan_status           object
device_type           object
plan_start_date       object
plan_end_date         object
gender                object
age_group             object
age                    int64
campaign_id           object
utm_source            object
utm_campaign          object
assignment_id         object
experiment_id         object
experiment_name       object
variant               object
assigned_at           object
dtype: object

## 1. pricing_ab - 5월



pricing_ab 테스트에 할당된 user 중 A/B test 할당 날짜 이후 구독 plan을 시작한 유저 수 산출

In [86]:
pricing_ab = ab_df[ab_df['experiment_name'] == 'pricing_ab']

variant_a = ab_df[(ab_df['experiment_name'] == 'pricing_ab') &
                  (ab_df['variant'] == 'A')]
variant_b = ab_df[(ab_df['experiment_name'] == 'pricing_ab') &
                  (ab_df['variant'] == 'B')]

In [87]:
variant_a['plan_start_date'] = pd.to_datetime(variant_a['plan_start_date'])
variant_a['assigned_at'] = pd.to_datetime(variant_a['assigned_at'])
variant_b['plan_start_date'] = pd.to_datetime(variant_b['plan_start_date'])
variant_b['assigned_at'] = pd.to_datetime(variant_b['assigned_at'])

/tmp/ipython-input-1487158650.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variant_a['plan_start_date'] = pd.to_datetime(variant_a['plan_start_date'])
/tmp/ipython-input-1487158650.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variant_a['assigned_at'] = pd.to_datetime(variant_a['assigned_at'])
/tmp/ipython-input-1487158650.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in 

In [88]:
filtered_a = variant_a[variant_a['plan_start_date'] > variant_a['assigned_at']]
filtered_b = variant_b[variant_b['plan_start_date'] > variant_b['assigned_at']]

In [89]:
count_a = filtered_a['subscription_plan'].value_counts()
count_b = filtered_b['subscription_plan'].value_counts()

In [90]:
print("Variant A - subscription_plan 상태 분포:")
print(count_a)
print("\nVariant B - subscription_plan 상태 분포:")
print(count_b)

Variant A - subscription_plan 상태 분포:
subscription_plan
monthly_pro      44
monthly_basic    38
annual_basic     38
annual_pro       38
Name: count, dtype: int64

Variant B - subscription_plan 상태 분포:
subscription_plan
monthly_pro      47
monthly_basic    43
annual_basic     39
annual_pro       31
Name: count, dtype: int64


In [65]:
count_a.sum()

np.int64(158)

## 2. onboarding_cta - 6월

In [92]:
variant_a3 = ab_df[(ab_df['experiment_name'] == 'onboarding_cta') &
                  (ab_df['variant'] == 'original')]
variant_b3 = ab_df[(ab_df['experiment_name'] == 'onboarding_cta') &
                  (ab_df['variant'] == 'test')]

In [94]:
variant_a3['plan_start_date'] = pd.to_datetime(variant_a3['plan_start_date'])
variant_a3['assigned_at'] = pd.to_datetime(variant_a3['assigned_at'])
variant_b3['plan_start_date'] = pd.to_datetime(variant_b3['plan_start_date'])
variant_b3['assigned_at'] = pd.to_datetime(variant_b3['assigned_at'])

/tmp/ipython-input-654361062.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variant_a3['plan_start_date'] = pd.to_datetime(variant_a3['plan_start_date'])
/tmp/ipython-input-654361062.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variant_a3['assigned_at'] = pd.to_datetime(variant_a3['assigned_at'])
/tmp/ipython-input-654361062.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in

In [96]:
filtered_a3 = variant_a3[variant_a3['plan_start_date'] > variant_a3['assigned_at']]
filtered_b3 = variant_b3[variant_b3['plan_start_date'] > variant_b3['assigned_at']]

In [97]:
count_a3 = filtered_a3['subscription_plan'].value_counts()
count_b3 = filtered_b3['subscription_plan'].value_counts()

In [99]:
print("Variant original - subscription_plan 상태 분포:")
print(count_a3)
print("\nVariant test - subscription_plan 상태 분포:")
print(count_b3)

Variant original - subscription_plan 상태 분포:
subscription_plan
annual_basic     18
monthly_pro      18
monthly_basic    18
annual_pro       11
Name: count, dtype: int64

Variant test - subscription_plan 상태 분포:
subscription_plan
monthly_pro      23
annual_basic     18
monthly_basic    17
annual_pro       12
Name: count, dtype: int64


In [100]:
count_a3.sum()

np.int64(65)

## 3. checkout_design - 7월

In [101]:
variant_a2 = ab_df[(ab_df['experiment_name'] == 'checkout_design') &
                  (ab_df['variant'] == 'control')]
variant_b2 = ab_df[(ab_df['experiment_name'] == 'checkout_design') &
                  (ab_df['variant'] == 'redesign')]

In [102]:
variant_a2['plan_start_date'] = pd.to_datetime(variant_a2['plan_start_date'])
variant_a2['assigned_at'] = pd.to_datetime(variant_a2['assigned_at'])
variant_b2['plan_start_date'] = pd.to_datetime(variant_b2['plan_start_date'])
variant_b2['assigned_at'] = pd.to_datetime(variant_b2['assigned_at'])

/tmp/ipython-input-2542942989.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variant_a2['plan_start_date'] = pd.to_datetime(variant_a2['plan_start_date'])
/tmp/ipython-input-2542942989.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variant_a2['assigned_at'] = pd.to_datetime(variant_a2['assigned_at'])
/tmp/ipython-input-2542942989.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats

In [103]:
filtered_a2 = variant_a2[variant_a2['plan_start_date'] > variant_a2['assigned_at']]
filtered_b2 = variant_b2[variant_b2['plan_start_date'] > variant_b2['assigned_at']]

In [104]:
count_a2 = filtered_a2['subscription_plan'].value_counts()
count_b2 = filtered_b2['subscription_plan'].value_counts()

In [107]:
filtered_a2

user_id           created_at         last_seen_at  \
1313  usr_d280f820d260  2025-07-05 09:30:45  2025-07-21 03:29:00   
1326  usr_39ac98a44532  2025-07-07 07:22:17  2025-07-19 08:32:00   
1346  usr_7c9f0851d778  2025-07-12 17:09:00  2025-07-20 08:20:00   
1352  usr_c56f9f0bff8d  2025-07-13 16:23:03  2025-07-21 16:33:00   
1362  usr_71a5fb33b008  2025-07-13 20:04:29  2025-07-21 14:22:00   

                     email acquisition_source subscription_plan plan_status  \
1313   yeeun51@example.org         google_cpc        annual_pro      active   
1326        qi@example.com         google_cpc      annual_basic      active   
1346      xyun@example.net         google_cpc        annual_pro      active   
1352        hi@example.net         google_cpc        annual_pro      active   
1362  seoboram@example.net         google_cpc      annual_basic      active   

     device_type plan_start_date plan_end_date  ... age_group age  \
1313         web      2025-07-21           NaN  ...       40s  48   
1326         web      2025-07-19           NaN  ...       40s  42   
1346         ios      2025-07-20           NaN  ...       20s  24   
1352         web      2025-07-21           NaN  ...       20s  26   
1362         ios      2025-07-21           NaN  ...       30s  32   

      campaign_id utm_source utm_campaign    assignment_id experiment_id  \
1313      cmp_001   facebook     spring24  ab_6bf29b272d0e    exp_202503   
1326      cmp_001   facebook     spring24  ab_40ed93fbf9ac    exp_202503   
1346      cmp_002   referral    ref_buddy  ab_61cc4426230b    exp_202503   
1352      cmp_001   facebook     spring24  ab_c7a152d9696a    exp_202503   
1362      cmp_001   facebook     spring24  ab_cc4c040aee44    exp_202503   

      experiment_name  variant         assigned_at  
1313  checkout_design  control 2025-07-05 09:30:45  
1326  checkout_design  control 2025-07-07 07:22:17  
1346  checkout_design  control 2025-07-12 17:09:00  
1352  checkout_design  control 2025-07-13 16:23:03  
1362  checkout_design  control 2025-07-13 20:04:29  

[5 rows x 21 columns]

In [105]:
print("Variant control - subscription_plan 상태 분포:")
print(count_a2)
print("\nVariant redesign - subscription_plan 상태 분포:")
print(count_b2)

Variant control - subscription_plan 상태 분포:
subscription_plan
annual_pro      3
annual_basic    2
Name: count, dtype: int64

Variant redesign - subscription_plan 상태 분포:
subscription_plan
annual_basic     5
monthly_basic    1
Name: count, dtype: int64


# 카이제곱 검정

In [19]:
from scipy.stats import chi2_contingency

## 1. Pricing_ab

In [21]:
# 총 인원수
total_a = 429
total_b = 450

# 가입자 수 (플랜별 합)
subscribers_a = 44 + 38 + 38 + 38  # 합계
subscribers_b = 47 + 43 + 39 + 31  # 합계

# 2x2 표 생성
table1 = [
    [subscribers_a, total_a - subscribers_a],  # Variant A: 가입자, 비가입자
    [subscribers_b, total_b - subscribers_b]   # Variant B: 가입자, 비가입자
]

chi2, p, dof, expected = chi2_contingency(table1)

print("Chi-square Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("\nExpected Frequencies:\n", expected)


Chi-square Statistic: 0.10419498043072856
p-value: 0.746852414034721
Degrees of Freedom: 1

Expected Frequencies:
 [[155.20136519 273.79863481]
 [162.79863481 287.20136519]]


-> p-value > 0.05 이므로 귀무가설 **("Pricing A/B test 후 결과는 동일하다.")** 채택

## 2. Onboarding CTA

In [23]:
# 총 인원수
total_original = 200
total_test = 207

# 가입자 수 (플랜별 합)
subscribers_original = 18 + 18 + 18 + 11  # 65명
subscribers_test = 23 + 18 + 17 + 12      # 70명

# 2x2 표 만들기 (가입자 vs 비가입자)
table2 = [
    [subscribers_original, total_original - subscribers_original],
    [subscribers_test, total_test - subscribers_test]
]

chi2, p, dof, expected = chi2_contingency(table2)

print("Chi-square Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("\nExpected Frequencies:\n", expected)

Chi-square Statistic: 0.031222869337616643
p-value: 0.8597440868027868
Degrees of Freedom: 1

Expected Frequencies:
 [[ 66.33906634 133.66093366]
 [ 68.66093366 138.33906634]]


-> p-value > 0.05 이므로 귀무가설 **("Onboarding CTA A/B test 후 결과는 동일하다.")** 채택

## 3. Checkout design

### 이전 코드

In [10]:
data2 = {
    'monthly_pro':  [0, 0],
    'monthly_basic': [0, 1],
    'annual_basic': [2, 5],
    'annual_pro':   [3, 0]
}

contingency_table3 = pd.DataFrame(data2, index=['Variant A', 'Variant B'])

# monthly_pro 제거
contingency_table3_reduced = contingency_table3.drop(columns=['monthly_pro'])

chi2_3, p_3, dof_3, expected_3 = chi2_contingency(contingency_table3_reduced)

print("Chi-square Statistic:", chi2_3)
print("p-value:", p_3)
print("Degrees of Freedom:", dof_3)
print("\nExpected Frequencies:\n", expected_3)


Chi-square Statistic: 5.238095238095239
p-value: 0.07287223191492671
Degrees of Freedom: 2

Expected Frequencies:
 [[0.45454545 3.18181818 1.36363636]
 [0.54545455 3.81818182 1.63636364]]


### 수정코드

In [24]:
# 총 인원수
total_control = 60
total_redesign = 71

# 가입자 수 (플랜별 합)
subscribers_control = 3 + 2  # 5명
subscribers_redesign = 5 + 1 # 6명

# 2x2 표 만들기 (가입자 vs 비가입자)
table3 = [
    [subscribers_control, total_control - subscribers_control],
    [subscribers_redesign, total_redesign - subscribers_redesign]
]

chi2, p, dof, expected = chi2_contingency(table3)

print("Chi-square Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("\nExpected Frequencies:\n", expected)

Chi-square Statistic: 0.0
p-value: 1.0
Degrees of Freedom: 1

Expected Frequencies:
 [[ 5.03816794 54.96183206]
 [ 5.96183206 65.03816794]]


-> p-value > 0.05 이므로 귀무가설 **("Checkout design A/B test 후 결과는 동일하다.")** 채택